- PF_Client/Redux/store.js
> redux store

- PF_Client/Redux/store.js
- PF_Client/src/app.jsx
Borrado el App autogenerado por create react App 
recodeado por uno escalable a medida que vayamos implementando los distintos modulos
> App recodeada

- PF_Api/src/models/Product.js
> model Product

- PF_Api/src/controllers/productControllers.js
- PF_Api/src/controllers/serviceControllers.js
- PF_Api/src/controllers/userControllers.js
Creatin controller folder, productController.js, serviceController.js and userController.js
> Creating folder and just files JS

- PF_Api/src/routes/index.js
- PF_Api/src/routes/productRouter.js
> ruta product creada

- try1.ts
> utils and product routes

- PF_Api/src/models/Product.js
- PF_Api/src/routes/productRouter.js
- PF_Api/src/utils/utils.js
llenado automatico de tabla Products con Api externa para poder visualizar en front
> llenado tabla Products con API

- PF_Api/src/controllers/productControllers.js
- PF_Api/src/controllers/serviceControllers.js
- PF_Api/src/controllers/userControllers.js
- PF_Api/src/handlers/productHandlers.js
- PF_Api/src/handlers/serviceHandlers.js
- PF_Api/src/handlers/userHandlers.js
user:creator,getters
product: creator, getters
service: creator, getters
just structure, not logic
> feat(PF_api/controllers): add module exports

- PF_Api/src/controllers/productControllers.js
- PF_Api/src/routes/productRouter.js
- PF_Api/src/utils/utils.js
route get all product
http://localhost:3001/product
route get product
http://localhost:3001/product?name=iPhone 9
> route get all products

- PF_Api/package.json
- PF_Api/src/models/User.js
- PF_Api/src/routes/index.js
- PF_Api/src/routes/userRouter.js
Se creo el modelo User, y se hizo ruta User. Sé que aún tiene detalles, favor ayudarme a revisar.
> Haciendo ruta User provisional

- PF_Api/src/controllers/userControllers.js
- PF_Api/src/handlers/userHandlers.js
- PF_Api/src/routes/userRouter.js
cleaning route code
locating try catch into handler
locating logic into controller
> relocating(routes/userRouter): locating logic

- PF_Api/src/controllers/productControllers.js
- PF_Api/src/handlers/productHandlers.js
- PF_Api/src/routes/productRouter.js
- PF_Api/src/utils/utils.js
correccion error ruta products
> correccion errores get all products

- PF_Api/src/controllers/userControllers.js
Se actualizó la creación, la búsqueda por id, edición de usuario y eliminación de usuario. Revisar avances.
> Updt rutas de usuario, crear, por id, editar, eliminar

- PF_Api/src/controllers/userControllers.js
- PF_Api/src/handlers/userHandlers.js
- PF_Api/src/routes/userRouter.js
Bryan fijate si te parece así. No lo pude probar porque no estoy pudiendo conectar el postgres. Igual faltan conectar algunas rutas al sequelize.
> Modularice user controller handler

- PF_Api/src/controllers/productControllers.js
- PF_Api/src/handlers/productHandlers.js
route post created 
post type JSON
{
"name": "cellphone",
"description":"hello this is the best cellphone in the world",
"price":"60",
"image":["https://i.ibb.co/znL6nKy/dog-no-image.png"],
"stock":95,
"userId":2
}
> Product post

- PF_Api/src/db.js
> coment lines error DB

- PF_Api/src/controllers/questionsControllers.js
- PF_Api/src/db.js
- PF_Api/src/handlers/questionsHandlers.js
- PF_Api/src/models/QuestProd.js
- PF_Api/src/models/QuestServ.js
- PF_Api/src/routes/index.js
- PF_Api/src/routes/questionsRouter.js
Probado que no rompe el resto del código. No funcionan todavía las Questions, pero no afecta el resto del código.
> Feat questions

- PF_Api/src/controllers/userControllers.js
- PF_Api/src/handlers/userHandlers.js
- PF_Api/src/routes/userRouter.js
Ya se puede crear usuario, editar usuario, obtener todos, obtener por id, eliminar. Favor revisar. Gracias.
> Ruta post, create, delete, edit de User Terminadas

- PF_Api/index.js
- PF_Api/src/controllers/questionsControllers.js
- PF_Api/src/db.js
- PF_Api/src/handlers/questionsHandlers.js
- PF_Api/src/models/QuestProd.js
- PF_Api/src/models/QuestServ.js
Renombrado de modelos de questions, por ahora se guardan y consultan correctamente los datos.
> Fix questions

- PF_Client/package-lock.json
- PF_Client/package.json
- PF_Client/src/Redux/actions.js
- PF_Client/src/Redux/reducer.js
- PF_Client/src/app.jsx
- PF_Client/src/components/NavBar/NavBar.jsx
- PF_Client/src/components/NavBar/SearchBar/SearchBar.jsx
- PF_Client/src/views/Create/Create.jsx
- PF_Client/src/views/Create/Create.module.css
- PF_Client/src/views/Create/validate.js
- PF_Client/vite.config.js
> Form final

- PF_Api/src/routes/questServRouter.js
Pequeño error que genere a ultimo momento arreglado el require de quest serv router
> Fix quest routes

- PF_Api/index.js
- PF_Api/src/controllers/questionsControllers.js
- PF_Api/src/handlers/questionsHandlers.js
Agregada la opcion de busqueda de las preguntas por producto.
> Feat quest getters

- PF_Api/src/controllers/serviceControllers.js
- PF_Api/src/handlers/serviceHandlers.js
- PF_Api/src/models/Service.js
- PF_Api/src/routes/serviceRouter.js
y modifique el modelo service para que incluya imagen
> ruta delete service completa

- PF_Client/src/Redux/actions.js
- PF_Client/src/Redux/reducer.js
- PF_Client/src/components/Filters/Filters.jsx
- PF_Client/src/views/Home/Home.jsx
Terminado con estilos y funcionamiento el filtro por precios.
> Tomas filters try

- PF_Api/index.js
- PF_Api/src/controllers/questionsControllers.js
- PF_Api/src/db.js
- PF_Api/src/handlers/questionsHandlers.js
- PF_Api/src/routes/questProdRouter.js
- PF_Api/src/routes/questServRouter.js
Agregado el getter por cliente, por oferta (prod o serv) y el delete. Falta el getter por vendedor. 
Limpiado de codigo tambien.
> Add quest gett

- PF_Client/src/components/NavBar/NavBar.jsx
Lleva a autenticación. 
El componente Log out renderiza una vez ingresado el usuario.
> Renderiza el componente Log in

- PF_Client/src/components/NavBar/NavBar.jsx
Se renderiza Mi perfil cuando el usuario inicia sesión
> Mi perfil aparece solo cuando se inicia sesión

- PF_Client/src/views/Landing/Landing.jsx
- PF_Client/src/views/Landing/Landing.module.css
- PF_Client/src/views/ProductDetail/ProductDetail.jsx
- PF_Client/src/views/ProductDetail/ProductDetail.module.css
Modificado el Landing
Modificado el ProductDetail para ciclar imagenes
> Landing & Detail refactor

- PF_Client/src/components/Auth0/Logiin/LoginButton.jsx
- PF_Client/src/components/NavBar/NavBar.jsx
- PF_Client/src/views/Landing/Landing.jsx
Corrección en el back, para cargar los usuarios sin necesidad de levantar front. 
Al crear usuario o iniciar sesión con google, ya se crea el usuario en la base de datos
> Creación de usuarios a la base de Datos

- PF_Api/index.js
- PF_Api/src/controllers/userControllers.js
- PF_Api/src/handlers/userHandlers.js
- PF_Api/src/models/User.js
Ya renderiza el profile, utilizando directamente la info del User en la base de datos.
> Perfil renderiza con la info del user directo en la BD

- PF_Client/src/Redux/actions.js
- PF_Client/src/Redux/reducer.js
- PF_Client/src/components/Auth0/Profile/Profile.jsx
Renderiza con la info de user de la BD
> Renderiza profile con la info de la BD del User

- PF_Client/src/components/Card/CardProducts/CardProducts.jsx
- PF_Client/src/components/Card/CardProducts/CardProducts.module.css
- PF_Client/src/components/Sections/Sections.module.css
- PF_Client/src/views/Landing/Landing.module.css
> Mejora estetica

- PF_Api/src/handlers/userHandlers.js
- PF_Client/src/components/Auth0/Profile/Profile.jsx
- PF_Client/src/components/NavBar/NavBar.jsx
- PF_Client/src/views/Home/Home.jsx
- PF_Client/src/views/Landing/Landing.jsx
- d34b9c183cdb728e742cbc7e82009efbd4064368
Ya se puede editar la información del perfil. Aún con unos detallitos, pero la lógica ya está
> Editar profile

- PF_Client/src/components/BotonIrInicio/BotonIrInicio.jsx
- PF_Client/src/components/Footer/Footer.jsx
- PF_Client/src/components/NavBar/NavBar.jsx
- PF_Client/src/components/NavBar/SearchBar/SearchBar.jsx
- PF_Client/src/views/Checkout/Checkout.jsx
Cambios de etiqueta <a>   a la etiqueta Link en todos los componentes.
> Cambios de etiqueta <a>   a la etiqueta Link en todos los componentes.

- PF_Api/index.js
- PF_Api/src/controllers/userControllers.js
- PF_Client/src/components/Card/CardProducts/CardProducts.module.css
- PF_Client/src/views/Home/Home.jsx
- PF_Client/src/views/Landing/Landing.jsx
> Perfil renderiza Ok

- PF_Api/src/controllers/productControllers.js
- PF_Api/src/models/Product.js
Agregue gender y category en el back. Así puedo insertarlo en el form de creación de producto y dsp en los filters.
> Agrege gender y category en product en el back-end

- PF_Api/index.js
- PF_Api/src/controllers/questionsControllers.js
- PF_Client/src/app.jsx
- PF_Client/src/components/Auth0/Profile/Profile.jsx
- PF_Client/src/components/Card/CardProducts/CardProducts.module.css
- PF_Client/src/components/Detail/Detail.jsx
- PF_Client/src/components/NavBar/NavBar.jsx
- PF_Client/src/components/Questions/ModalBtn.jsx
- PF_Client/src/components/Questions/Questions.jsx
- PF_Client/src/views/Create/Create.jsx
- PF_Client/src/views/Home/Home.jsx
- PF_Client/src/views/ProductDetail/ProductDetail.jsx
- PF_Client/src/views/ServiceDetail/ServiceDetail.jsx
Solucionado lo del id del vendedor en crear productos
Avanzando con las preguntas
> Questprod front

- PF_Api/index.js
- PF_Api/src/controllers/questionsControllers.js
- PF_Client/src/app.jsx
- PF_Client/src/components/Auth0/Profile/Profile.jsx
- PF_Client/src/components/Detail/Detail.jsx
- PF_Client/src/components/NavBar/NavBar.jsx
- PF_Client/src/components/Questions/ModalBtn.jsx
- PF_Client/src/components/Questions/Questions.jsx
- PF_Client/src/views/Create/Create.jsx
- PF_Client/src/views/Home/Home.jsx
- PF_Client/src/views/Landing/Landing.jsx
- PF_Client/src/views/ProductDetail/ProductDetail.jsx
- PF_Client/src/views/ServiceDetail/ServiceDetail.jsx
Ya se creó un perfil de administrador. Pendiente organizar los componentes a mostrar cuando entre a este perfil. 
Nota: Enviarme los correos para darles asignación de administrador
> Creado un perfil de administrado

- PF_Client/src/app.jsx
- PF_Client/src/components/Auth0/Profile/Profile.jsx
- PF_Client/src/components/NavBar/NavBar.jsx
- PF_Client/src/components/SectionsAdmin/SectionsAdmin.jsx
- PF_Client/src/components/SectionsAdmin/SectionsAdmin.module.css
- PF_Client/src/components/UserList/UserList.jsx
- PF_Client/src/views/Home/Home.jsx
Ya aparece correctamente Log Out en el Profile, cuando se accede con usuario de Admin.
> Corregido profile en usuario Admin, ya aparece LOG OUT

- PF_Client/src/components/BotonIrInicio/BotonIrInicio.jsx
- PF_Client/src/components/Card/Card.jsx
- PF_Client/src/components/UserList/UserList.jsx
Ya solo pueden acceder a ella los usuarios Admin
> Ruta Users protegida, solo pueden entrar los admin

- PF_Client/src/components/CardUser/CardUser/CardUser.jsx
- PF_Client/src/components/CardUser/CardUsers.jsx
Ya está renderizado el ícono para bloquear y desbloquear. Trabajando aún en la lógica del código.
> Icono para bloquear y desbloquear usuarios

- PF_Client/src/app.jsx
- PF_Client/src/components/Filters/Filters.jsx
- PF_Client/src/components/Iconos/Iconos.jsx
- PF_Client/src/components/Iconos/Iconos.module.css
- PF_Client/src/views/Home/Home.jsx
Al hacer click en Vender ya no lleva directamente al formulario, el usuario ahora puede elegir si va a publicar un producto o servicio y dsp lo envía a la ruta correspondiente. Servicios todavía no hace nada por q no está creado.
> Agregó componente Iconos para crear producto o servicios

- PF_Api/PF_Api documantacion.md
- PF_Api/index.js
- PF_Api/src/controllers/cartController.js
- PF_Api/src/handlers/cartHandler.js
Agregando funcionalidades de rutas de carrito, mejorando algunas fallas (agregar otro producto al carrito, eliminar producto del carrito, que devuelva el carrito con los productos despues de crear o modificar, buscar carrito por pk, buscar todos los carritos.
> Cart route

- PF_Client/package-lock.json
- PF_Client/src/components/Auth0/Profile/Profile.jsx
- PF_Client/src/redux/actions.js
Actualiza el perfil del usuario. Ya no redirige al home
> perfil Actualiza correctamente

- PF_Client/src/app.jsx
- PF_Client/src/components/Auth0/Logiin/LoginButton.module.css
- PF_Client/src/components/Auth0/Logout/LogoutButton.module.css
- PF_Client/src/components/BotonIrInicio/BotonIrInicio.jsx
- PF_Client/src/components/Card/Card.jsx
- PF_Client/src/components/Card/Card.module.css
- PF_Client/src/components/Card/CardProducts/CardProducts.jsx
- PF_Client/src/components/Card/CardProducts/CardProducts.module.css
- PF_Client/src/components/Card/SliderProduct/SliderProduct.jsx
- PF_Client/src/components/Card/SliderProduct/SliderProduct.module.css
- PF_Client/src/components/Cart/Cart.jsx
- PF_Client/src/components/Cart/Cart.module.css
- PF_Client/src/components/Cart/CartProducts/CartProducts.module.css
- PF_Client/src/components/Categories/Categories.jsx
- PF_Client/src/components/Categories/Categories.module.css
- PF_Client/src/components/Iconos/Iconos.jsx
- PF_Client/src/components/NavBar/NavBar.jsx
- PF_Client/src/components/NavBar/NavBar.module.css
- PF_Client/src/components/NavBar/SearchBar/SearchBar.jsx
- PF_Client/src/components/NavBar/SearchBar/SearchBar.module.css
- PF_Client/src/components/Sections/Sections.jsx
- PF_Client/src/components/Sections/Sections.module.css
- PF_Client/src/redux/actions.js
- PF_Client/src/redux/reducer.js
- PF_Client/src/views/Favourites/Favourites.jsx
- PF_Client/src/views/Favourites/Favourites.module.css
- PF_Client/src/views/Home/Home.jsx
Añadi estado favourites a reducer
Añadi carpeta Favourites con jsx y css
Añadi la ruta favourites en app
Favoritos funcionalidad
En servicios quitar carrusel y secciones
En home, añadir ofertas y ver todo
Boton ir inicio arreglado
Responsive home, carrito y buscador
Mejoras en cart
> Muchos cambiis

- PF_Api/src/routes/index.js
- PF_Api/src/utils/auth0.js
creada proteccion de rutas, aun comentado a espera de modificacion del front
> ProtectedRoutes

- PF_Api/package.json
- PF_Client/src/components/Card/CardProducts/CardProducts.jsx
- PF_Client/src/components/Cart/Cart.jsx
- PF_Client/src/redux/actions.js
- PF_Client/src/redux/reducer.js
El carrito actualiza el valor. Ya va una parte solucionada
> carrito actualiza
